### ISSUE TITLE
matplotlib error

### ISSUE THREAD

**Issue by bg5s12** [merlresearch/hyper-unmix#1]
C:\Users\Vinicius Lima\Downloads\hyper-unmix-main\hyper-unmix-main>cd C:\Users\Vinicius Lima\Downloads\hyper-unmix-main\hyper-unmix-main

C:\Users\Vinicius Lima\Downloads\hyper-unmix-main\hyper-unmix-main>python interface.py
C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\lazy_loader\__init__.py:185: RuntimeWarning: subpackages can technically be lazily loaded, but it causes the package to be eagerly loaded even if it is already lazily loaded.So, you probably shouldn't use subpackages with this lazy feature.
  warnings.warn(msg, RuntimeWarning)
C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\lazy_loader\__init__.py:185: RuntimeWarning: subpackages can technically be lazily loaded, but it causes the package to be eagerly loaded even if it is already lazily loaded.So, you probably shouldn't use subpackages with this lazy feature.
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\Vinicius Lima\Downloads\hyper-unmix-main\hyper-unmix-main\interface.py", line 20, in <module>
    from separate import DEFAULT_PRE_TRAINED_MODEL_PATH
  File "C:\Users\Vinicius Lima\Downloads\hyper-unmix-main\hyper-unmix-main\separate.py", line 12, in <module>
    from hyperbolic_separator import HyperbolicSigSep
  File "C:\Users\Vinicius Lima\Downloads\hyper-unmix-main\hyper-unmix-main\hyperbolic_separator.py", line 10, in <module>
    from pytorch_lightning import LightningModule
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\utilities\types.py", line 25, in <module>
    from torchmetrics import Metric
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\functional\audio\pit.py", line 23, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\metric.py", line 42, in <module>
    from torchmetrics.utilities.plot import _AX_TYPE, _PLOT_OUT_TYPE, plot_single_or_multi_val
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchmetrics\utilities\plot.py", line 28, in <module>
    _PLOT_OUT_TYPE = Tuple[plt.Figure, Union[matplotlib.axes.Axes, np.ndarray]]
                                             ^^^^^^^^^^^^^^^
  File "C:\Users\Vinicius Lima\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\_api\__init__.py", line 226, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'axes'. Did you mean: 'axis'?

**Comment by gwichern** [comment]
This seems to be an issue with your python environment setup. One thing I noticed is it looks like you are using python 3.11, but the code has only been tested with python 3.9 as mentioned in the README. Please reopen if the issue persists.
